/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      { hostname: 'm.media-amazon.com' },
      { hostname: 'i.etsystatic.com' },
      { hostname: 'i.ebayimg.com' },
      { hostname: 'i.pinimg.com' },
      { hostname: 'rangreza.net' },
      { hostname: 'salitexonline.com' },
      { hostname: 'www.fabricoz.com' },
      { hostname: 'stilento.com' },
      { hostname: 'declarepakistan.com' },
      { hostname: 'karigari.com.pk' },
      { hostname: 'shoprex.com' },
      { hostname: 'mubashrawardrobe.com' },
      { hostname: 'theworldofhsy.com' },
      { hostname: 'www.nameerabyfarooq.com' },
      { hostname: 'www.ammarakhan.com' },
      { hostname: 'getethnic.com' },
      { hostname: 'www.pkbridals.ca' },
      { hostname: 'cdn.shopify.com' },
      { hostname: 'empress-clothing.com' },
      { hostname: 'rjspret.com' },
      { hostname: 'ishdeena.com' },
      { hostname: 'kapdavilla.com' },
      { hostname: 'www.textileexport.in' },
      { hostname: 'kajols.com' },
      { hostname: 'assets2.andaazfashion.com' },
      { hostname: 'sillhouete.com' },
      { hostname: 'hatkebride.com' },
      { hostname: 'filhaal.co.uk' },
      { hostname: 'www.786shop.com' },
      { hostname: 'www.designerdhaage.com' },
      { hostname: 'peachmode.com' },
      { hostname: 'www.yourlibaas.com' },
      { hostname: 'inayatarts.pk' },
      { hostname: 'hijabulhareem.com' },
      { hostname: 'pk-live-21.slatic.net' },
      { hostname: 'fashionsense.com.pk' },
      { hostname: 'suraiya.pk' },
      { hostname: 'www.dhaagey.pk' },
      { hostname: 'eastessence.com' },
      { hostname: 'alsanaya.com' },
      { hostname: 'i0.wp.com' },
      { hostname: 'tgmstore.pk' },
      { hostname: 'images.pexels.com' },
    ],
  },
};

module.exports = nextConfig;