// lib/products-pk.js — Pakistani Garment Collection
// Generated from scraped data with real product images
// Products: 50

export const products = [
  {
    id: 'zahra-lawn-ensemble-1',
    name: 'Gulshan-e-Zahra',
    category: 'Lawn Suits',
    price: 'PKR 14,500',
    images: [
      'https://m.media-amazon.com/images/I/61FXO10RklL._AC_UY1000_.jpg',
      'https://rangreza.net/cdn/shop/files/D-7Front_A_2400x2400_27348c55-b971-416c-aa05-5e183f9c66ea.jpg?v=1759176994&width=1080',
      'https://i.etsystatic.com/8029584/r/il/90f70a/7519611053/il_570xN.7519611053_dgmj.jpg',
    ],
    image: 'https://m.media-amazon.com/images/I/61FXO10RklL._AC_UY1000_.jpg',
    colors: [
      { name: 'Mint Green',   hex: '#B2FFFC' },
      { name: 'Dusky Pink',   hex: '#E4D6F5' },
      { name: 'Ivory White',  hex: '#FFFFFF' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Indulge in the whimsical beauty of our Gulshan-e-Zahra lawn suit, where delicate florals dance across a soft mint green backdrop. With intricate embroidery and a flowing silhouette, this ensemble is perfect for warm summer days and elegant gatherings.',
    details: {
      material: 'High-quality lawn fabric with a lightweight weave and a subtle sheen, ensuring a comfortable and breathable wear',
      fit:      "Loose-fitting silhouette with a relaxed A-line cut. Model is 5'8\" wearing size M.",
      care:     'Hand wash separately in cold water, do not bleach, and iron on reverse side to preserve the delicate embroidery.',
    },
  },
  {
    id: 'lahore-embroidered-lawn-suit',
    name: 'Gulbahar Luxury Lawn Suit',
    category: 'Lawn Suits',
    price: 'PKR 32,000',
    images: [
      'https://rangreza.net/cdn/shop/files/D-7Front_A_2400x2400_27348c55-b971-416c-aa05-5e183f9c66ea.jpg?v=1759176994&width=1080',
      'https://i.etsystatic.com/8029584/r/il/90f70a/7519611053/il_570xN.7519611053_dgmj.jpg',
      'http://salitexonline.com/cdn/shop/files/minawebpic_0028_editIMG_4354.webp?v=1765053612',
    ],
    image: 'https://rangreza.net/cdn/shop/files/D-7Front_A_2400x2400_27348c55-b971-416c-aa05-5e183f9c66ea.jpg?v=1759176994&width=1080',
    colors: [
      { name: 'Mint Green',   hex: '#ACFFAC' },
      { name: 'Soft Peach',   hex: '#FFD7BE' },
      { name: 'Ivory Cream',  hex: '#FFFFF0' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegance personified, the Gulbahar Luxury Lawn Suit is a masterful blend of intricate embroidery and flowing silhouettes, perfect for the modern Pakistani woman who values both style and modesty. The intricate embroidery work on the front and back of the shirt, along with the beautifully crafted dupatta, makes this suit a true showstopper.',
    details: {
      material: 'High-quality lawn fabric with a soft, smooth texture and a subtle sheen, woven with a blend of cotton and silk threads',
      fit:      "Relaxed, flowy silhouette with a fitted bodice and a flared shalwar. Model is 5'8\" wearing size M.",
      care:     'Dry clean or hand wash in cold water. Do not bleach or iron while wet.',
    },
  },
  {
    id: 'zahra-lawn-suit-1',
    name: 'Gulshan-e-Zahra Classic',
    category: 'Lawn Suits',
    price: 'PKR 12,500',
    images: [
      'https://i.etsystatic.com/8029584/r/il/90f70a/7519611053/il_570xN.7519611053_dgmj.jpg',
      'http://salitexonline.com/cdn/shop/files/minawebpic_0028_editIMG_4354.webp?v=1765053612',
      'https://www.fabricoz.com/cdn/shop/files/Pakistani-Dress-C1327B_2_600x600.jpg?v=1762746644',
    ],
    image: 'https://i.etsystatic.com/8029584/r/il/90f70a/7519611053/il_570xN.7519611053_dgmj.jpg',
    colors: [
      { name: 'Mint Green',  hex: '#B2FFFC' },
      { name: 'Peach',       hex: '#FFD7BE' },
      { name: 'Ivory',       hex: '#FFFFF0' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Step into the serene beauty of Gulshan-e-Zahra, a lawn suit that embodies the essence of spring. With intricate floral patterns and a soft pastel palette, this ensemble is perfect for warm weather occasions. The delicate embroidery and subtle sheen of the fabric evoke a sense of understated elegance.',
    details: {
      material: 'High-quality lawn fabric with a smooth weave and a subtle sheen, weighing 120 grams per meter',
      fit:      "Fitted silhouette with a relaxed fit through the hips and thighs. Model is 5'8\" wearing size M.",
      care:     'Hand wash separately in cold water, do not bleach, iron on reverse side while still slightly damp.',
    },
  },
  {
    id: 'zarina-lawn-suit-2024',
    name: 'Gulmohar Bloom',
    category: 'Lawn Suits',
    price: 'PKR 28,000',
    images: [
      'http://salitexonline.com/cdn/shop/files/minawebpic_0028_editIMG_4354.webp?v=1765053612',
      'https://www.fabricoz.com/cdn/shop/files/Pakistani-Dress-C1327B_2_600x600.jpg?v=1762746644',
      'http://stilento.com/cdn/shop/products/0034_049A8588_700x_920f4ebf-09fd.jpg?v=1671389160',
    ],
    image: 'http://salitexonline.com/cdn/shop/files/minawebpic_0028_editIMG_4354.webp?v=1765053612',
    colors: [
      { name: 'Mint Green',   hex: '#B2FFFC' },
      { name: 'Soft Peach',   hex: '#FFD7BE' },
      { name: 'Ivory Cream',  hex: '#FFF599' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Step into the warmth of summer with Gulmohar Bloom, a captivating lawn suit that embodies the essence of Pakistani flora. This exquisite ensemble features intricate floral patterns and delicate embroidery, bringing a touch of elegance to your everyday look.',
    details: {
      material: 'High-quality lawn fabric with a smooth, silky texture and a subtle sheen, woven with a blend of cotton and polyester',
      fit:      "Relaxed fit with a flowing silhouette. Model is 5'8\" wearing size M.",
      care:     'Hand wash in cold water, gentle cycle. Do not bleach or iron. Dry flat.',
    },
  },
  {
    id: 'zarmina-lawn-suit-1',
    name: 'Gulbadan Lawn Suit',
    category: 'Lawn Suits',
    price: 'PKR 14,500',
    images: [
      'https://www.fabricoz.com/cdn/shop/files/Pakistani-Dress-C1327B_2_600x600.jpg?v=1762746644',
      'http://stilento.com/cdn/shop/products/0034_049A8588_700x_920f4ebf-09fd.jpg?v=1671389160',
      'https://m.media-amazon.com/images/I/61FXO10RklL._AC_UY1000_.jpg',
    ],
    image: 'https://www.fabricoz.com/cdn/shop/files/Pakistani-Dress-C1327B_2_600x600.jpg?v=1762746644',
    colors: [
      { name: 'Mint Green',  hex: '#ACFFAC' },
      { name: 'Soft Peach',  hex: '#FFD7BE' },
      { name: 'Cream',       hex: '#FFF599' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your warm-weather wardrobe with the Gulbadan Lawn Suit, featuring intricate floral patterns and delicate embroidery that dances across the fabric. With its soft, breathable fabric and flowing silhouette, you\'ll feel like a vision of loveliness in this stunning lawn suit.',
    details: {
      material: 'High-quality lawn fabric with a smooth, lustrous finish and a subtle sheen, woven with a blend of cotton and polyester',
      fit:      "Loose, flowing silhouette with a relaxed fit through the body and a flared hem. Model is 5'8\" wearing size M.",
      care:     'Hand wash in cold water, gentle cycle. Do not bleach or iron. Dry flat to preserve the fabric.',
    },
  },
  {
    id: 'lawn-suit-mashriq-6',
    name: 'Zeenat E Gul',
    category: 'Lawn Suits',
    price: 'PKR 18,500',
    images: [
      'http://declarepakistan.com/cdn/shop/files/P1100_9.png?v=1717153026',
      'http://salitexonline.com/cdn/shop/files/0037__0034_RAF_9016copy.webp?v=1759577679',
      'http://karigari.com.pk/cdn/shop/products/Three-Piece-Lawn-Suit-1_3e58916f-d5dd-4890-bf05-dd7f9d5faedc.jpg?v=1679990480',
    ],
    image: 'http://declarepakistan.com/cdn/shop/files/P1100_9.png?v=1717153026',
    colors: [
      { name: 'Mint Green',  hex: '#B2FFFC' },
      { name: 'Soft Peach',  hex: '#FFD7BE' },
      { name: 'Ivory',       hex: '#FFFFF0' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegance personified, the Zeenat E Gul lawn suit is a masterclass in understated luxury. With intricate floral patterns dancing across its soft mint green and ivory fabric, this three-piece ensemble is perfect for warm weather gatherings and special occasions.',
    details: {
      material: 'High-quality lawn fabric with a smooth, lightweight weave and a subtle sheen, perfect for spring and summer',
      fit:      "Relaxed, flowing silhouette with a fitted bodice and a flowing shalwar. Model is 5'8\" wearing size M.",
      care:     'Delicate wash in cold water, gentle cycle. Do not bleach or iron.',
    },
  },
  {
    id: 'gulmohar-summer-dress',
    name: 'Gulmohar Bloom Suit',
    category: 'Lawn Suits',
    price: 'PKR 18,500',
    images: [
      'http://salitexonline.com/cdn/shop/files/0037__0034_RAF_9016copy.webp?v=1759577679',
      'http://karigari.com.pk/cdn/shop/products/Three-Piece-Lawn-Suit-1_3e58916f-d5dd-4890-bf05-dd7f9d5faedc.jpg?v=1679990480',
      'https://shoprex.com/images/srproducts/large/3-piece-digital-printed-lawn-suit-with-chiffon-duppata_44529.jpg',
    ],
    image: 'http://salitexonline.com/cdn/shop/files/0037__0034_RAF_9016copy.webp?v=1759577679',
    colors: [
      { name: 'Mint Green',  hex: '#B2FFFC' },
      { name: 'Soft Peach',  hex: '#FFD7BE' },
      { name: 'Cream',       hex: '#FFF599' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Step into the warmth of summer with our Gulmohar Bloom Suit, a delightful lawn ensemble adorned with intricate florals and subtle embroidery. The soft pastel hues evoke the gentle beauty of the gulmohar tree in full bloom, while the flowy silhouette ensures a comfortable and elegant fit.',
    details: {
      material: 'High-quality lawn fabric with a soft, smooth texture and a subtle sheen, weighing 120 grams per meter',
      fit:      "Relaxed, flowy silhouette with a V-neckline and cap sleeves. Model is 5'8\" wearing size M.",
      care:     'Hand wash in cold water, gentle cycle. Do not bleach or iron. Dry in shade.',
    },
  },
  {
    id: 'zarine-lawn-suit-1',
    name: 'Zarine Lawn Suit',
    category: 'Lawn Suits',
    price: 'PKR 12,500',
    images: [
      'http://karigari.com.pk/cdn/shop/products/Three-Piece-Lawn-Suit-1_3e58916f-d5dd-4890-bf05-dd7f9d5faedc.jpg?v=1679990480',
      'https://shoprex.com/images/srproducts/large/3-piece-digital-printed-lawn-suit-with-chiffon-duppata_44529.jpg',
      'https://mubashrawardrobe.com/wp-content/uploads/2025/05/Maria-B-Lawn-3-Piece-Embroidered-Suit-Worn-Model.jpeg',
    ],
    image: 'http://karigari.com.pk/cdn/shop/products/Three-Piece-Lawn-Suit-1_3e58916f-d5dd-4890-bf05-dd7f9d5faedc.jpg?v=1679990480',
    colors: [
      { name: 'Mint Green',   hex: '#B2FFFC' },
      { name: 'Soft Peach',   hex: '#FFD7BE' },
      { name: 'Ivory White',  hex: '#FFFFFF' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your summer wardrobe with the Zarine Lawn Suit, a masterful blend of comfort and elegance. This exquisite ensemble features intricate floral patterns and delicate embroidery, set against a soft pastel backdrop that shimmers in the light.',
    details: {
      material: 'High-quality lawn fabric with a smooth, silky texture and a subtle sheen, woven with a blend of cotton and polyester',
      fit:      "Relaxed, flowy silhouette with a fitted bodice and a flared sleeves. Model is 5'8\" wearing size M.",
      care:     'Machine wash cold, gentle cycle. Do not bleach or iron. Dry flat.',
    },
  },
  {
    id: 'zarina-lawn-suit-9',
    name: 'Gulbahar Lawn Suit',
    category: 'Lawn Suits',
    price: 'PKR 12,500',
    images: [
      'https://shoprex.com/images/srproducts/large/3-piece-digital-printed-lawn-suit-with-chiffon-duppata_44529.jpg',
      'https://mubashrawardrobe.com/wp-content/uploads/2025/05/Maria-B-Lawn-3-Piece-Embroidered-Suit-Worn-Model.jpeg',
      'http://salitexonline.com/cdn/shop/files/0020__0051_RAF_8619copy.webp?v=1759580728',
    ],
    image: 'https://shoprex.com/images/srproducts/large/3-piece-digital-printed-lawn-suit-with-chiffon-duppata_44529.jpg',
    colors: [
      { name: 'Mint Green',   hex: '#B2FFFC' },
      { name: 'Powder Pink',  hex: '#E4D6F5' },
      { name: 'Ivory White',  hex: '#FFFFFF' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegance personified, the Gulbahar Lawn Suit is a masterclass in understated sophistication. With intricate floral patterns dancing across the fabric, this ensemble is perfect for warm weather gatherings and special occasions.',
    details: {
      material: 'High-quality lawn fabric with a soft, smooth texture and a subtle sheen, woven with a blend of cotton and polyester',
      fit:      "Loose, flowy silhouette with a relaxed fit through the body and a flared hem. Model is 5'8\" wearing size M.",
      care:     'Machine wash in cold water, gentle cycle. Do not bleach or iron while wet. Dry cleaning recommended.',
    },
  },
  {
    id: 'zahra-lawn-suit-2023',
    name: 'Gulbahar Garden Lawn',
    category: 'Lawn Suits',
    price: 'PKR 12,500',
    images: [
      'https://mubashrawardrobe.com/wp-content/uploads/2025/05/Maria-B-Lawn-3-Piece-Embroidered-Suit-Worn-Model.jpeg',
      'http://salitexonline.com/cdn/shop/files/0020__0051_RAF_8619copy.webp?v=1759580728',
      'http://declarepakistan.com/cdn/shop/files/P1100_9.png?v=1717153026',
    ],
    image: 'https://mubashrawardrobe.com/wp-content/uploads/2025/05/Maria-B-Lawn-3-Piece-Embroidered-Suit-Worn-Model.jpeg',
    colors: [
      { name: 'Mint Green',  hex: '#B2FFFC' },
      { name: 'Cream',       hex: '#FFF599' },
      { name: 'Blush Pink',  hex: '#FFC5C5' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Step into the warmth of summer with our Gulbahar Garden Lawn, a masterful blend of comfort and elegance. This exquisite ensemble features intricate floral patterns and delicate embroidery, evoking the beauty of a lush garden in full bloom.',
    details: {
      material: 'High-quality lawn fabric with a soft, breathable weave and a subtle sheen, perfect for warm weather',
      fit:      "Loose-fitting silhouette with a relaxed waist and flowing sleeves. Model is 5'8\" wearing size M.",
      care:     'Hand wash in cold water, mild detergent recommended. Do not bleach or iron.',
    },
  },
  // ─── SHALWAR KAMEEZ ────────────────────────────────────────────────────────
  {
    id: 'zarine-ensemble-11',
    name: 'Gulshan Shalwar Kameez',
    category: 'Shalwar Kameez',
    price: 'PKR 18,500',
    images: [
      'https://i.etsystatic.com/25292473/r/il/7c77ac/6230803411/il_570xN.6230803411_cmna.jpg',
      'https://i.ebayimg.com/images/g/5nEAAOSwBm9mzW7X/s-l1200.jpg',
      'https://m.media-amazon.com/images/I/71x-+3kGNVL._AC_UY1000_.jpg',
    ],
    image: 'https://i.etsystatic.com/25292473/r/il/7c77ac/6230803411/il_570xN.6230803411_cmna.jpg',
    colors: [
      { name: 'Mocha',      hex: '#964B00' },
      { name: 'Cream',      hex: '#FFF599' },
      { name: 'Dusky Pink', hex: '#E4D6F5' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegance personified, the Gulshan Shalwar Kameez is a masterful blend of traditional craftsmanship and modern flair, with intricate embroidery adorning the kameez and a flowing shalwar that drapes majestically. The Mocha and Cream hues evoke the warmth of a Pakistani sunset.',
    details: {
      material: 'Made from a luxurious blend of cotton and silk, with a soft, smooth texture and a subtle sheen',
      fit:      "Classic, flowing silhouette with a relaxed fit through the body and a tapered shalwar. Model is 5'8\" wearing size M.",
      care:     'Dry cleaning or hand washing in cold water recommended. Iron while fabric is still slightly damp.',
    },
  },
  {
    id: 'lahore-luxury-shalwar-kameez-12',
    name: 'Zarina Embellished Lawn Shalwar Kameez',
    category: 'Shalwar Kameez',
    price: 'PKR 18,000',
    images: [
      'https://i.ebayimg.com/images/g/5nEAAOSwBm9mzW7X/s-l1200.jpg',
      'https://m.media-amazon.com/images/I/71x-+3kGNVL._AC_UY1000_.jpg',
      'https://i.ebayimg.com/images/g/XvkAAOSweKlmzW7Y/s-l1200.jpg',
    ],
    image: 'https://i.ebayimg.com/images/g/5nEAAOSwBm9mzW7X/s-l1200.jpg',
    colors: [
      { name: 'Mint Green',   hex: '#B2FFFC' },
      { name: 'Soft Peach',   hex: '#FFD7BE' },
      { name: 'Ivory Cream',  hex: '#FFF599' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your wardrobe with the Zarina Embellished Lawn Shalwar Kameez, featuring intricate floral motifs and delicate beadwork on a soft mint green lawn fabric. The flowing silhouette and V-neckline create a flattering, modest look perfect for special occasions.',
    details: {
      material: 'High-quality lawn fabric with a smooth, lightweight texture and a subtle sheen, perfect for warm weather',
      fit:      "Relaxed, flowing silhouette with a V-neckline and cap sleeves. Model is 5'8\" wearing size M.",
      care:     'Dry clean or hand wash in cold water. Iron on a low heat setting to preserve embroidery and beadwork.',
    },
  },
  {
    id: 'mehndi-nights-13',
    name: 'Nur-e-Razzaq',
    category: 'Shalwar Kameez',
    price: 'PKR 32,000',
    images: [
      'https://m.media-amazon.com/images/I/71x-+3kGNVL._AC_UY1000_.jpg',
      'https://i.ebayimg.com/images/g/XvkAAOSweKlmzW7Y/s-l1200.jpg',
      'https://m.media-amazon.com/images/I/716kB6hHVuL._AC_UY1000_.jpg',
    ],
    image: 'https://m.media-amazon.com/images/I/71x-+3kGNVL._AC_UY1000_.jpg',
    colors: [
      { name: 'Midnight Blue', hex: '#1a1d23' },
      { name: 'Cream',         hex: '#f5f5f5' },
      { name: 'Rich Gold',     hex: '#ffd700' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegant and understated, the Nur-e-Razzaq Shalwar Kameez is a masterclass in subtle sophistication, with intricate hand-embroidered florals dancing across the midnight blue fabric like the soft glow of moonlight on a summer evening.',
    details: {
      material: 'Luxurious cotton blend with a subtle sheen, crafted from high-quality fabric with a smooth weave, 250 grams per meter',
      fit:      "Flattering A-line silhouette with a relaxed fit through the hips and thighs. Model is 5'8\" wearing size M.",
      care:     'Hand wash separately in cold water, do not bleach or tumble dry. Iron while still slightly damp.',
    },
  },
  {
    id: 'zafran-embroidered-luxury-shalwar-kameez-14',
    name: 'Gulmohar Bloom Shalwar Kameez',
    category: 'Shalwar Kameez',
    price: 'PKR 28,000',
    images: [
      'https://i.ebayimg.com/images/g/XvkAAOSweKlmzW7Y/s-l1200.jpg',
      'https://m.media-amazon.com/images/I/716kB6hHVuL._AC_UY1000_.jpg',
      'https://cdn.shopify.com/s/files/1/0589/1322/6961/files/Fully_Stitched_Black_White_Pakistani_Tunic_Style_Salwar_Kameez_With_Organza_Dupatta-6_480x480.jpg?v=1723810409',
    ],
    image: 'https://i.ebayimg.com/images/g/XvkAAOSweKlmzW7Y/s-l1200.jpg',
    colors: [
      { name: 'Dewy Morn',      hex: '#C9E4CA' },
      { name: 'Soft Sage',      hex: '#BCE3C5' },
      { name: 'Blushing Bloom', hex: '#FFC5C5' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegance personified, the Gulmohar Bloom Shalwar Kameez is a masterful blend of traditional craftsmanship and modern flair, featuring intricate zafran embroidery that dances across the luxurious fabric like the first whispers of spring.',
    details: {
      material: 'Crafted from high-quality, imported cotton silk with a subtle sheen, this fabric boasts a smooth, lustrous texture and a flowing drape',
      fit:      "Classic, flowing silhouette with a relaxed fit through the body and a flared shalwar. Model is 5'8\" wearing size M.",
      care:     'Dry cleaning or hand washing in cold water with mild detergent. Iron while the fabric is still slightly damp.',
    },
  },
  {
    id: 'pakistan-garden-delight-15',
    name: 'Gulbahar Shalwar Kameez',
    category: 'Shalwar Kameez',
    price: 'PKR 28,000',
    images: [
      'https://i.pinimg.com/736x/78/20/4c/78204c83177804c53ed34a1fa46e72ef.jpg',
      'https://i.etsystatic.com/59227288/r/il/5fbdf6/6970383128/il_570xN.6970383128_372b.jpg',
      'https://assets2.andaazfashion.com/media/catalog/product/cache/1/image/500x750/a12781a7f2ccb3d663f7fd01e1bd2e4e/b/l/black-silk-embroidered-pakistani-trouser-suit-lstv114608-1.jpg',
    ],
    image: 'https://i.pinimg.com/736x/78/20/4c/78204c83177804c53ed34a1fa46e72ef.jpg',
    colors: [
      { name: 'Mint Green',  hex: '#B2FFFC' },
      { name: 'Rich Gold',   hex: '#FFD700' },
      { name: 'Soft Cream',  hex: '#FFF599' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'The Gulbahar Shalwar Kameez is a masterful blend of traditional craftsmanship and modern elegance, featuring intricate floral patterns and delicate embroidery that evoke the serenity of a Pakistani garden at dawn.',
    details: {
      material: 'Made from high-quality lawn cotton with a subtle sheen, lightweight, breathable, and perfect for warm weather',
      fit:      "Relaxed, flowy silhouette with a fitted kameez and loose, tapered shalwar. Model is 5'8\" wearing size M.",
      care:     'Hand washing in cold water and line drying. Avoid machine washing, bleaching, or ironing.',
    },
  },
  {
    id: 'lahore-embroidered-luxury-shalwar-kameez',
    name: 'Mehndi Raat Shalwar Kameez',
    category: 'Shalwar Kameez',
    price: 'PKR 32,000',
    images: [
      'https://i.etsystatic.com/59227288/r/il/5fbdf6/6970383128/il_570xN.6970383128_372b.jpg',
      'https://assets2.andaazfashion.com/media/catalog/product/cache/1/image/500x750/a12781a7f2ccb3d663f7fd01e1bd2e4e/b/l/black-silk-embroidered-pakistani-trouser-suit-lstv114608-1.jpg',
      'https://i.etsystatic.com/25292473/r/il/7c77ac/6230803411/il_570xN.6230803411_cmna.jpg',
    ],
    image: 'https://i.etsystatic.com/59227288/r/il/5fbdf6/6970383128/il_570xN.6970383128_372b.jpg',
    colors: [
      { name: 'Mocha',         hex: '#964B00' },
      { name: 'Seafoam Green', hex: '#B2E6CE' },
      { name: 'Rich Gold',     hex: '#FFD700' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Experience the opulence of traditional Pakistani embroidery with the Mehndi Raat Shalwar Kameez, where intricate floral patterns dance across a rich, mocha-hued backdrop. Delicate seafoam green accents and subtle gold threading evoke the soft glow of moonlit nights.',
    details: {
      material: 'Luxurious silk blend with intricate cotton embroidery, weighing 350 grams per meter, with a smooth, lustrous weave',
      fit:      "Tailored, flowing silhouette with a relaxed fit through the body and a subtle flare at the hem. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. To preserve the intricate embroidery, avoid machine washing.',
    },
  },
  {
    id: 'zarina-embroidered-luxury-shalwar-kameez-17',
    name: 'Zarina Embroidered Luxury Shalwar Kameez',
    category: 'Shalwar Kameez',
    price: 'PKR 32,000',
    images: [
      'https://assets2.andaazfashion.com/media/catalog/product/cache/1/image/500x750/a12781a7f2ccb3d663f7fd01e1bd2e4e/b/l/black-silk-embroidered-pakistani-trouser-suit-lstv114608-1.jpg',
      'https://i.etsystatic.com/25292473/r/il/7c77ac/6230803411/il_570xN.6230803411_cmna.jpg',
      'https://i.etsystatic.com/46614237/r/il/f9b781/6725907670/il_fullxfull.6725907670_f10g.jpg',
    ],
    image: 'https://assets2.andaazfashion.com/media/catalog/product/cache/1/image/500x750/a12781a7f2ccb3d663f7fd01e1bd2e4e/b/l/black-silk-embroidered-pakistani-trouser-suit-lstv114608-1.jpg',
    colors: [
      { name: 'Mocha',      hex: '#964B00' },
      { name: 'Soft Peach', hex: '#FFD7BE' },
      { name: 'Mint Green', hex: '#B2FFFC' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your formal wardrobe with the Zarina Embroidered Luxury Shalwar Kameez, featuring intricate floral motifs and delicate thread work that shimmers in the light. The soft mocha, peach, and mint hues evoke the serene beauty of a Pakistani sunset.',
    details: {
      material: 'Rich silk blend with intricate embroidery and sequin work, weighing 350 grams per meter, with a smooth weave and a subtle sheen',
      fit:      "Slim-fit silhouette with a relaxed shalwar and a fitted kameez. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Iron at low temperature. Avoid machine washing.',
    },
  },
  {
    id: 'zarine-embroidered-luxury-shalwar-kameez',
    name: 'Zarine Embroidered Luxury Shalwar Kameez',
    category: 'Shalwar Kameez',
    price: 'PKR 32,000',
    images: [
      'https://i.etsystatic.com/25292473/r/il/7c77ac/6230803411/il_570xN.6230803411_cmna.jpg',
      'https://i.etsystatic.com/46614237/r/il/f9b781/6725907670/il_fullxfull.6725907670_f10g.jpg',
      'https://i.etsystatic.com/48802170/r/il/3ca5b3/7231539250/il_570xN.7231539250_aszj.jpg',
    ],
    image: 'https://i.etsystatic.com/25292473/r/il/7c77ac/6230803411/il_570xN.6230803411_cmna.jpg',
    colors: [
      { name: 'Mocha',      hex: '#964B00' },
      { name: 'Mint Green', hex: '#B2FFFC' },
      { name: 'Rich Plum',  hex: '#660066' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your formal wardrobe with the Zarine Embroidered Luxury Shalwar Kameez, featuring intricate thread work and motifs that dance across the fabric. The Zarine\'s mocha, mint, and plum hues evoke the warmth and vibrancy of Pakistani culture.',
    details: {
      material: 'Luxurious silk-blend fabric with a soft, lustrous finish and a subtle sheen, woven with a dense weave for durability and comfort',
      fit:      "Flowing, relaxed silhouette with a fitted kameez and loose, wide-leg shalwar. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Avoid exposure to direct sunlight and moisture.',
    },
  },
  // ─── BRIDAL & FORMAL ───────────────────────────────────────────────────────
  {
    id: 'zarineh-bridal-ensemble-19',
    name: 'Zarineh Jahan',
    category: 'Bridal & Formal',
    price: 'PKR 42,000',
    images: [
      'https://i.etsystatic.com/10917356/r/il/2214ea/1296691416/il_570xN.1296691416_ixfz.jpg',
      'https://theworldofhsy.com/cdn/shop/files/049A1255.jpg?v=1760511989&width=533',
      'https://www.nameerabyfarooq.com/cdn/shop/products/TraditionalRedPakistaniBridalDressinPishwasFrockBridalLehengaStylePakistaniWeddingDress_180x.jpg?v=1670006146',
    ],
    image: 'https://i.etsystatic.com/10917356/r/il/2214ea/1296691416/il_570xN.1296691416_ixfz.jpg',
    colors: [
      { name: 'Mocha Cream', hex: '#F5F5DC' },
      { name: 'Rich Gold',   hex: '#FFD700' },
      { name: 'Deep Berry',  hex: '#660066' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Embark on a regal journey with the Zarineh Jahan, a majestic bridal ensemble adorned with intricate gold embroidery and delicate sequins. This opulent outfit is a masterful blend of traditional craftsmanship and modern elegance, perfect for making a statement on your special day.',
    details: {
      material: 'Luxurious silk and velvet blend with intricate gold and silver threading, featuring a dense, plush weave and a subtle sheen',
      fit:      "Classic, tailored silhouette with a fitted bodice and flowing skirt. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Avoid exposure to direct sunlight and moisture. Store in a cool, dry place.',
    },
  },
  {
    id: 'zahra-bridal-luxury-gharara-20',
    name: 'Mah-e-Nur Gharara',
    category: 'Bridal & Formal',
    price: 'PKR 45,000',
    images: [
      'https://theworldofhsy.com/cdn/shop/files/049A1255.jpg?v=1760511989&width=533',
      'https://www.nameerabyfarooq.com/cdn/shop/products/TraditionalRedPakistaniBridalDressinPishwasFrockBridalLehengaStylePakistaniWeddingDress_180x.jpg?v=1670006146',
      'https://www.ammarakhan.com/cdn/shop/files/13_2e13442e-f087-4772-8b41-54e551197bf8.jpg?format=webp&v=1752764471&width=320',
    ],
    image: 'https://theworldofhsy.com/cdn/shop/files/049A1255.jpg?v=1760511989&width=533',
    colors: [
      { name: 'Midnight Blue', hex: '#1a1d23' },
      { name: 'Mocha Beige',   hex: '#f5f5dc' },
      { name: 'Rich Gold',     hex: '#ffd700' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Make an unforgettable entrance in the Mah-e-Nur Gharara, a breathtaking ensemble of intricate zardozi and resham embroidery on a richly hued midnight blue silk base, perfectly complemented by delicate mocha beige and gold accents.',
    details: {
      material: 'Pure silk with intricate zardozi and resham embroidery, backed with a layer of fine cotton for added comfort and structure',
      fit:      "Flared, floor-sweeping gharara silhouette with a fitted, long-sleeved bodice. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Avoid exposure to direct sunlight and moisture.',
    },
  },
  {
    id: 'zehra-bridal-jora-21',
    name: 'Zehra Jora',
    category: 'Bridal & Formal',
    price: 'PKR 45,000',
    images: [
      'https://www.nameerabyfarooq.com/cdn/shop/products/TraditionalRedPakistaniBridalDressinPishwasFrockBridalLehengaStylePakistaniWeddingDress_180x.jpg?v=1670006146',
      'https://www.ammarakhan.com/cdn/shop/files/13_2e13442e-f087-4772-8b41-54e551197bf8.jpg?format=webp&v=1752764471&width=320',
      'https://getethnic.com/wp-content/uploads/2021/12/Pakistani-Bridal-Lehenga-13-1.jpg',
    ],
    image: 'https://www.nameerabyfarooq.com/cdn/shop/products/TraditionalRedPakistaniBridalDressinPishwasFrockBridalLehengaStylePakistaniWeddingDress_180x.jpg?v=1670006146',
    colors: [
      { name: 'Mehndi Green', hex: '#34C759' },
      { name: 'Rich Gold',    hex: '#FFD700' },
      { name: 'Crimson Red',  hex: '#DC143C' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'The Zehra Jora is a masterpiece of Pakistani craftsmanship, with intricate hand-embroidery and delicate sequins that shimmer like the night sky. This exquisite ensemble is a perfect blend of traditional and modern, featuring a fitted, long-sleeved bodice and a flowing, flared lehenga.',
    details: {
      material: 'Made from luxurious silk and organza, with intricate embroidery and sequin work',
      fit:      "Fitted bodice with a flared, floor-sweeping lehenga. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Avoid exposure to direct sunlight and moisture.',
    },
  },
  {
    id: 'zaraah-bridal-jora-11',
    name: 'Zaraah Bridal Jora',
    category: 'Bridal & Formal',
    price: 'PKR 45,000',
    images: [
      'https://www.ammarakhan.com/cdn/shop/files/13_2e13442e-f087-4772-8b41-54e551197bf8.jpg?format=webp&v=1752764471&width=320',
      'https://getethnic.com/wp-content/uploads/2021/12/Pakistani-Bridal-Lehenga-13-1.jpg',
      'https://www.pkbridals.ca/wp-content/uploads/2024/08/White-and-Gold-Bridal-Lehenga.webp',
    ],
    image: 'https://www.ammarakhan.com/cdn/shop/files/13_2e13442e-f087-4772-8b41-54e551197bf8.jpg?format=webp&v=1752764471&width=320',
    colors: [
      { name: 'Midnight Bloom', hex: '#343a40' },
      { name: 'Rose Petal',     hex: '#ffc5c5' },
      { name: 'Ivory Cream',    hex: '#f5f5f5' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your wedding day look with the Zaraah Bridal Jora, a masterpiece of intricate embroidery and delicate florals on a rich midnight bloom background. The luxurious fabric drapes elegantly, creating a regal silhouette that shines with every step.',
    details: {
      material: 'Heavy silk with intricate gold and silver embroidery, adorned with delicate sequins and beads',
      fit:      "Floor-sweeping, mermaid-cut silhouette with a fitted bodice and flared hem. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Avoid exposure to direct sunlight and extreme heat.',
    },
  },
  {
    id: 'zara-sheer-bridal-lehnga-23',
    name: 'Jashan E Ishq',
    category: 'Bridal & Formal',
    price: 'PKR 45,000',
    images: [
      'https://i.ebayimg.com/images/g/cKcAAOSwuXpkVO-c/s-l400.jpg',
      'https://cdn.shopify.com/s/files/1/1762/5129/files/women-in-pakistani-anarkali-suit.jpg?v=1637394238',
      'http://empress-clothing.com/cdn/shop/collections/D10-GOSSAMER.jpg?v=1688736182',
    ],
    image: 'https://i.ebayimg.com/images/g/cKcAAOSwuXpkVO-c/s-l400.jpg',
    colors: [
      { name: 'Midnight Bloom', hex: '#8b0a1a' },
      { name: 'Royal Cream',    hex: '#f5f5dc' },
      { name: 'Soft Sage',      hex: '#bce3c5' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegance embodied, Jashan E Ishq is a masterful blend of traditional craftsmanship and modern sophistication, with intricate embroidery and subtle beading that shimmers like moonlight on a summer\'s night. A true showstopper for the discerning bride.',
    details: {
      material: 'Rich silk fabric with intricate silver and gold embroidery, adorned with delicate sequins and beads',
      fit:      "Flared, floor-sweeping silhouette with a fitted bodice and flowing skirt. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Store in a cool, dry place away from direct sunlight.',
    },
  },
  {
    id: 'zahra-bridal-jora-24',
    name: "Zahra's Moonlit Dreams",
    category: 'Bridal & Formal',
    price: 'PKR 45,000',
    images: [
      'https://cdn.shopify.com/s/files/1/1762/5129/files/women-in-pakistani-anarkali-suit.jpg?v=1637394238',
      'http://empress-clothing.com/cdn/shop/collections/D10-GOSSAMER.jpg?v=1688736182',
      'https://cdn.shopify.com/s/files/1/1762/5129/files/pakistani-anarkali-dress-in-white.jpg?v=1637394238',
    ],
    image: 'https://cdn.shopify.com/s/files/1/1762/5129/files/women-in-pakistani-anarkali-suit.jpg?v=1637394238',
    colors: [
      { name: 'Midnight Sky',     hex: '#1a1d23' },
      { name: 'Rose Petal',       hex: '#e4d6f5' },
      { name: 'Champagne Cream',  hex: '#f7f2c4' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Step into the enchanting world of Zahra\'s Moonlit Dreams, a breathtaking bridal jora that weaves together intricate threadwork, delicate lace, and majestic silk. With a soft, champagne-hued base and midnight sky accents, this show-stopping ensemble is the epitome of understated elegance.',
    details: {
      material: 'Heavy silk with intricate threadwork and delicate lace overlays, featuring a luxurious 300gsm weight and a smooth, lustrous weave',
      fit:      "Fitted, flared silhouette with a tailored bodice and flowing skirt. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Avoid exposure to direct sunlight and moisture.',
    },
  },
  {
    id: 'jamawar-bridal-gown-25',
    name: 'Zeenat Jahan',
    category: 'Bridal & Formal',
    price: 'PKR 35,000',
    images: [
      'http://empress-clothing.com/cdn/shop/collections/D10-GOSSAMER.jpg?v=1688736182',
      'https://cdn.shopify.com/s/files/1/1762/5129/files/pakistani-anarkali-dress-in-white.jpg?v=1637394238',
      'https://m.media-amazon.com/images/I/81fCJOT9q6L._AC_UY1000_.jpg',
    ],
    image: 'http://empress-clothing.com/cdn/shop/collections/D10-GOSSAMER.jpg?v=1688736182',
    colors: [
      { name: 'Mehndi Green',  hex: '#34C759' },
      { name: 'Raja Pink',     hex: '#FFC0CB' },
      { name: 'Midnight Blue', hex: '#1A1D23' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Inspired by the opulence of Mughal architecture, the Zeenat Jahan is a masterpiece of intricate embroidery and flowing silhouettes. This show-stopping bridal gown features delicate floral motifs and shimmering sequins, crafted to evoke the grandeur of a bygone era.',
    details: {
      material: 'Luxurious silk jamawar with intricate gold and silver embroidery, adorned with sequins and beads for added dimension',
      fit:      "Classic, floor-sweeping silhouette with a fitted bodice and flowing skirt. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Avoid exposure to direct sunlight and moisture.',
    },
  },
  {
    id: 'zehra-bridal-lahore-26',
    name: 'Nur-e-Zehra Jora',
    category: 'Bridal & Formal',
    price: 'PKR 48,000',
    images: [
      'https://cdn.shopify.com/s/files/1/1762/5129/files/pakistani-anarkali-dress-in-white.jpg?v=1637394238',
      'https://m.media-amazon.com/images/I/81fCJOT9q6L._AC_UY1000_.jpg',
      'http://rjspret.com/cdn/shop/products/Pari-2-1.png?v=1682965723',
    ],
    image: 'https://cdn.shopify.com/s/files/1/1762/5129/files/pakistani-anarkali-dress-in-white.jpg?v=1637394238',
    colors: [
      { name: 'Mehndi Green',    hex: '#34C759' },
      { name: 'Royal Crimson',   hex: '#8B0A1A' },
      { name: 'Champagne Beige', hex: '#F5F5DC' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Evoke the majesty of Mughal empresses in our exquisite Nur-e-Zehra Jora, a masterfully crafted ensemble adorned with intricate floral motifs, delicate gota work, and majestic zardozi embroidery that dances across the fabric like moonlight on a Lahore night.',
    details: {
      material: 'Rich silk fabric with intricate zardozi and gota work, carefully woven to provide a luxurious feel and a subtle sheen',
      fit:      "Tailored fit designed to accentuate the female form. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Store in a cool, dry place away from direct sunlight.',
    },
  },
  // ─── KURTIS ────────────────────────────────────────────────────────────────
  {
    id: 'zarine-kurti-27',
    name: 'Zarine Kurti',
    category: 'Kurtis',
    price: 'PKR 8,500',
    images: [
      'https://i.ebayimg.com/images/g/u40AAOSw-lpn0BRn/s-l1200.jpg',
      'https://ishdeena.com/cdn/shop/files/ishdeena-pakistani-kurtis-for-women-indian-style-cotton-tunics-womens-tops-printed-lawn-423038_1024x1024.jpg?v=1738458138',
      'https://m.media-amazon.com/images/I/61beaiQTdgL._AC_UY1100_.jpg',
    ],
    image: 'https://i.ebayimg.com/images/g/u40AAOSw-lpn0BRn/s-l1200.jpg',
    colors: [
      { name: 'Mocha',         hex: '#964B00' },
      { name: 'Seafoam Green', hex: '#B2E6CE' },
      { name: 'Rich Plum',     hex: '#660066' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your everyday look with the Zarine Kurti, a beautifully crafted piece featuring intricate embroidery and a soft, flowing silhouette. The mocha and seafoam green hues evoke the warmth of a Pakistani sunset, while the rich plum adds a touch of luxury.',
    details: {
      material: 'Made from a luxurious blend of cotton and silk, featuring a smooth, lustrous fabric with a subtle sheen, 220 gsm',
      fit:      "Relaxed, A-line silhouette with a V-neckline and cap sleeves. Model is 5'8\" wearing size M.",
      care:     'Dry cleaning or hand washing in cold water with mild detergent. Do not bleach or iron while wet.',
    },
  },
  {
    id: 'zarina-embroidered-kurti-29',
    name: 'Zarina Embroidered Kurti',
    category: 'Kurtis',
    price: 'PKR 12,000',
    images: [
      'https://m.media-amazon.com/images/I/61beaiQTdgL._AC_UY1100_.jpg',
      'https://i.etsystatic.com/25292473/r/il/612f69/3100012617/il_570xN.3100012617_91ux.jpg',
      'https://ishdeena.com/cdn/shop/files/ishdeena-pakistani-kurtis-for-women-indian-style-cotton-tunics-womens-tops-printed-lawn-907873_1024x1024.jpg?v=1738256948',
    ],
    image: 'https://m.media-amazon.com/images/I/61beaiQTdgL._AC_UY1100_.jpg',
    colors: [
      { name: 'Mocha',      hex: '#964B00' },
      { name: 'Ivory',      hex: '#FFFFF0' },
      { name: 'Soft Peach', hex: '#FFD7BE' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your everyday look with the Zarina Embroidered Kurti, featuring intricate floral motifs and delicate thread work that dance across the fabric. This stunning piece is perfect for special occasions or as a statement addition to your workwear wardrobe.',
    details: {
      material: 'High-quality cotton lawn with a smooth, lustrous finish and a medium weight of 200 gsm',
      fit:      "Relaxed, straight silhouette with a round neckline and side slits. Model is 5'8\" wearing size M.",
      care:     'Hand wash in cold water, gentle cycle. Do not bleach or iron while wet.',
    },
  },
  {
    id: 'zarine-kurti-31',
    name: 'Razia Embellished Kurti',
    category: 'Kurtis',
    price: 'PKR 8,500',
    images: [
      'https://kapdavilla.com/images/product/sub_images/2023/02/safa-fashion-fab-1074-exclusive-pakistani-print-kurti-pant-set-0-2023-02-16_15_57_40.jpeg',
      'https://www.textileexport.in/media/mceu_73175033211690872816597.jpg',
      'http://kajols.com/cdn/shop/products/print-multi-colour-casual-kurti-256924-1000x1375.jpg?v=1685001241',
    ],
    image: 'https://kapdavilla.com/images/product/sub_images/2023/02/safa-fashion-fab-1074-exclusive-pakistani-print-kurti-pant-set-0-2023-02-16_15_57_40.jpeg',
    colors: [
      { name: 'Mocha',      hex: '#964B00' },
      { name: 'Dusky Pink', hex: '#C99F86' },
      { name: 'Mint Green', hex: '#B2FFFC' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your everyday look with the Razia Embellished Kurti, featuring intricate hand-embroidery and delicate sequin work on a soft, mocha-hued fabric. The subtle sheen of the fabric catches the light, while the fitted silhouette and V-neckline create a flattering, modest silhouette.',
    details: {
      material: 'Made from a high-quality, lightweight cotton blend with a smooth, silky texture and a subtle sheen',
      fit:      "Fitted silhouette with a V-neckline and cap sleeves. Model is 5'8\" wearing size S.",
      care:     'Hand wash separately in cold water, do not bleach or iron on embellishments.',
    },
  },
  {
    id: 'zaahirah-embroidered-kurti',
    name: 'Zaahirah Embroidered Kurti',
    category: 'Kurtis',
    price: 'PKR 8,500',
    images: [
      'https://www.textileexport.in/media/mceu_73175033211690872816597.jpg',
      'http://kajols.com/cdn/shop/products/print-multi-colour-casual-kurti-256924-1000x1375.jpg?v=1685001241',
      'https://kapdavilla.com/images/product/sub_images/2023/02/safa-fashion-fab-1074-exclusive-pakistani-print-kurti-pant-set-2-2023-02-16_15_57_40.jpeg',
    ],
    image: 'https://www.textileexport.in/media/mceu_73175033211690872816597.jpg',
    colors: [
      { name: 'Mocha',      hex: '#964B00' },
      { name: 'Ivory',      hex: '#FFFFF0' },
      { name: 'Sage Green', hex: '#8B9467' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your everyday look with the Zaahirah Embroidered Kurti, featuring intricate floral motifs and delicate sequin work on a soft, mocha-hued backdrop. As the embroidered flowers dance across the fabric, you\'ll feel the essence of Pakistani craftsmanship and elegance.',
    details: {
      material: 'Made from a luxurious blend of cotton and silk, with a smooth, lustrous finish and a subtle sheen, medium weight with a slight texture',
      fit:      "Relaxed, A-line silhouette with a V-neckline and cap sleeves. Model is 5'8\" wearing size M.",
      care:     'Dry cleaning or hand washing in cold water. Gently reshape while damp and air dry away from direct sunlight.',
    },
  },
  {
    id: 'ishdeena-printed-kurti',
    name: 'Ishdeena Printed Lawn Kurti',
    category: 'Kurtis',
    price: 'PKR 5,500',
    images: [
      'https://ishdeena.com/cdn/shop/files/ishdeena-pakistani-kurtis-for-women-indian-style-cotton-tunics-womens-tops-printed-lawn-907873_1024x1024.jpg?v=1738256948',
      'https://ishdeena.com/cdn/shop/files/ishdeena-pakistani-kurtis-for-women-indian-style-cotton-tunics-womens-tops-printed-lawn-423038_1024x1024.jpg?v=1738458138',
      'https://i.etsystatic.com/25292473/r/il/612f69/3100012617/il_570xN.3100012617_91ux.jpg',
    ],
    image: 'https://ishdeena.com/cdn/shop/files/ishdeena-pakistani-kurtis-for-women-indian-style-cotton-tunics-womens-tops-printed-lawn-907873_1024x1024.jpg?v=1738256948',
    colors: [
      { name: 'Coral Print',  hex: '#FF6B6B' },
      { name: 'Blue Print',   hex: '#4169E1' },
      { name: 'Green Print',  hex: '#228B22' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    description: 'A versatile printed lawn kurti for the modern Pakistani woman — bold digital prints on breathable fabric make this an everyday essential. Pairs effortlessly with leggings, palazzos, or jeans for a complete modest look.',
    details: {
      material: '100% Cotton Lawn — Digital printed, pre-washed for softness',
      fit:      "Straight-cut, hip-length. Model is 5'6\" wearing size M.",
      care:     'Machine wash cold. Dry in shade. Iron on low.',
    },
  },
  // ─── OCCASION WEAR ─────────────────────────────────────────────────────────
  {
    id: 'maharani-gharara-11',
    name: "Zahra's Dream Gharara",
    category: 'Occasion Wear',
    price: 'PKR 32,000',
    images: [
      'https://i.pinimg.com/474x/24/c4/13/24c413a30bce93b6f2701da95c0a71bf.jpg',
      'https://cdn.shopify.com/s/files/1/1732/6543/files/Pakistani_Eid_Dresses_Trending_Pakistani_Party_Wear_for_Eid_480x480.jpg?v=1678982043',
      'https://hatkebride.com/cdn/shop/files/cropped_5600_54475778917_o_9e7c_3c89_ab319cd4-fae3-4994-bae4-f5fa1bcf4b45.jpg?v=1754425220&width=900',
    ],
    image: 'https://i.pinimg.com/474x/24/c4/13/24c413a30bce93b6f2701da95c0a71bf.jpg',
    colors: [
      { name: 'Mughal Green', hex: '#008000' },
      { name: 'Royal Blue',   hex: '#4169E1' },
      { name: 'Crimson Red',  hex: '#DC143C' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Inspired by the majestic architecture of the Mughal era, the Zahra\'s Dream Gharara is a masterful blend of traditional craftsmanship and modern elegance. This exquisite ensemble features intricate floral patterns and delicate embroidery, evoking the beauty of a bygone era.',
    details: {
      material: 'Rich silk fabric with intricate zardozi embroidery and subtle sheen, weighing 350 grams per meter',
      fit:      "Flared, floor-sweeping silhouette with a fitted waist. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Store in a cool, dry place away from direct sunlight.',
    },
  },
  {
    id: 'raat-ki-chandni-1',
    name: 'Raat Ki Chandni',
    category: 'Occasion Wear',
    price: 'PKR 28,000',
    images: [
      'https://cdn.shopify.com/s/files/1/1732/6543/files/Pakistani_Eid_Dresses_Trending_Pakistani_Party_Wear_for_Eid_480x480.jpg?v=1678982043',
      'https://hatkebride.com/cdn/shop/files/cropped_5600_54475778917_o_9e7c_3c89_ab319cd4-fae3-4994-bae4-f5fa1bcf4b45.jpg?v=1754425220&width=900',
      'http://filhaal.co.uk/cdn/shop/articles/Pakistani_Eid_Clothing_Collection_002e6c3a-8959-45ba-beff-e6b4061a51bc.png?v=1742959117',
    ],
    image: 'https://cdn.shopify.com/s/files/1/1732/6543/files/Pakistani_Eid_Dresses_Trending_Pakistani_Party_Wear_for_Eid_480x480.jpg?v=1678982043',
    colors: [
      { name: 'Midnight Blue',    hex: '#1a1d23' },
      { name: 'Luminous Silver',  hex: '#b1b8c3' },
      { name: 'Crimson Red',      hex: '#8b0a1a' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Ethereal and enchanting, the Raat Ki Chandni is a masterfully crafted ensemble that embodies the essence of Pakistani luxury. With intricate silver embroidery that shimmers like moonlight on a velvet expanse, this ensemble is perfect for making a statement at your next special occasion.',
    details: {
      material: 'Crafted from a rich blend of silk and velvet, with intricate silver embroidery and delicate beading',
      fit:      "Fitted bodice with a flowing, floor-length silhouette. Model is 5'8\" wearing size S.",
      care:     'Dry clean only. Store in a cool, dry place away from direct sunlight.',
    },
  },
  {
    id: 'zarine-embroidered-jumpsuit-35',
    name: 'Zarine Occasion Jumpsuit',
    category: 'Occasion Wear',
    price: 'PKR 38,000',
    images: [
      'https://hatkebride.com/cdn/shop/files/cropped_5600_54475778917_o_9e7c_3c89_ab319cd4-fae3-4994-bae4-f5fa1bcf4b45.jpg?v=1754425220&width=900',
      'http://filhaal.co.uk/cdn/shop/articles/Pakistani_Eid_Clothing_Collection_002e6c3a-8959-45ba-beff-e6b4061a51bc.png?v=1742959117',
      'https://cdn.shopify.com/s/files/1/1732/6543/files/Pakistani_Anarkali_Eid_Dresses_for_Eid_2023_480x480.jpg?v=1678982546',
    ],
    image: 'https://hatkebride.com/cdn/shop/files/cropped_5600_54475778917_o_9e7c_3c89_ab319cd4-fae3-4994-bae4-f5fa1bcf4b45.jpg?v=1754425220&width=900',
    colors: [
      { name: 'Midnight Blue', hex: '#1a1d23' },
      { name: 'Rich Crimson',  hex: '#8b0a1a' },
      { name: 'Mocha Beige',   hex: '#964b00' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your special occasions with the Zarine Occasion Jumpsuit, intricately embroidered with traditional Pakistani motifs on luxurious silk-chiffon. The flowing wide-leg silhouette and delicate cap sleeves exude elegance, while the subtle sheen of the fabric catches the light with every move.',
    details: {
      material: 'Silk-chiffon fabric with intricate thread embroidery, featuring a flowing drape and subtle sheen',
      fit:      "Loose, wide-leg silhouette with delicate cap sleeves. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Avoid exposure to direct sunlight or excessive heat.',
    },
  },
  {
    id: 'majestic-jalsa-gown-36',
    name: 'Zeenat Jalsa Gown',
    category: 'Occasion Wear',
    price: 'PKR 28,000',
    images: [
      'http://filhaal.co.uk/cdn/shop/articles/Pakistani_Eid_Clothing_Collection_002e6c3a-8959-45ba-beff-e6b4061a51bc.png?v=1742959117',
      'https://cdn.shopify.com/s/files/1/1732/6543/files/Pakistani_Anarkali_Eid_Dresses_for_Eid_2023_480x480.jpg?v=1678982546',
      'https://cdn.shopify.com/s/files/1/1762/5129/files/women-in-eid-clothing.jpg?v=1645871825',
    ],
    image: 'http://filhaal.co.uk/cdn/shop/articles/Pakistani_Eid_Clothing_Collection_002e6c3a-8959-45ba-beff-e6b4061a51bc.png?v=1742959117',
    colors: [
      { name: 'Midnight Blue', hex: '#1a1d23' },
      { name: 'Royal Crimson', hex: '#8b0a1a' },
      { name: 'Ivory Cream',   hex: '#f5f5f5' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegance personified, the Zeenat Jalsa Gown is a masterpiece of Pakistani craftsmanship, with intricate hand-embroidery and ornate sequins that dance across the midnight blue silk. Perfect for a lavish wedding or a high-society gala, this gown exudes refinement and poise.',
    details: {
      material: 'Luxurious silk fabric with a smooth, lustrous finish, intricately embroidered with silver and gold thread',
      fit:      "Floor-sweeping, mermaid silhouette with a fitted bodice and a dramatic flared skirt. Model is 5'8\" wearing size S.",
      care:     'Dry clean only. Avoid exposure to direct sunlight and moisture.',
    },
  },
  {
    id: 'nur-jahan-ensemble-1',
    name: 'Zeenat Jora',
    category: 'Occasion Wear',
    price: 'PKR 32,000',
    images: [
      'https://sillhouete.com/cdn/shop/files/3_f034a708-7341-46db-b641-c8122a567cd0.png?v=1721638031&width=1946',
      'https://i.etsystatic.com/61892596/r/il/226272/7262622505/il_570xN.7262622505_h89n.jpg',
      'https://cdn.shopify.com/s/files/1/1732/6543/files/Pakistani_Anarkali_Eid_Dresses_for_Eid_2023_480x480.jpg?v=1678982546',
    ],
    image: 'https://sillhouete.com/cdn/shop/files/3_f034a708-7341-46db-b641-c8122a567cd0.png?v=1721638031&width=1946',
    colors: [
      { name: 'Mocha',       hex: '#964B00' },
      { name: 'Midnight Blue',hex: '#1A1D23' },
      { name: 'Crimson Red', hex: '#8B0A1A' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegance personified, the Zeenat Jora is a masterful blend of intricate embroidery, flowing silhouettes, and rich fabrics, perfect for making a statement at your next formal event. The meticulous attention to detail and opulent hues evoke the grandeur of Mughal-era splendor.',
    details: {
      material: 'Velvet and silk blend with intricate gold and silver embroidery, featuring a subtle sheen and a luxurious weight of 400 gsm',
      fit:      "Flared, floor-sweeping silhouette with a fitted bodice and a relaxed, flowing skirt. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Avoid exposure to direct sunlight and excessive heat. Steam ironing recommended.',
    },
  },
  {
    id: 'zarineh-jashn-lehnga-39',
    name: 'Zarineh Jashn Lehnga',
    category: 'Occasion Wear',
    price: 'PKR 35,000',
    images: [
      'https://i.etsystatic.com/61892596/r/il/226272/7262622505/il_570xN.7262622505_h89n.jpg',
      'https://www.786shop.com/blogdata/images/large/Wedding-Season-5-11-07-23.jpg',
      'https://i.pinimg.com/474x/7e/8b/63/7e8b63c9ebe09f6cc536b55b258f5126.jpg',
    ],
    image: 'https://i.etsystatic.com/61892596/r/il/226272/7262622505/il_570xN.7262622505_h89n.jpg',
    colors: [
      { name: 'Midnight Bloom', hex: '#8B0A1A' },
      { name: 'Mocha Mist',     hex: '#964B00' },
      { name: 'Royal Garnet',   hex: '#6B0F23' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your special occasion style with the Zarineh Jashn Lehnga, a resplendent ensemble that weaves together intricate floral patterns, luxurious silk fabrics, and exquisite embroidery. The midnight bloom hue adds a touch of mystery, while the mocha mist and royal garnet accents evoke the warmth of traditional Pakistani celebrations.',
    details: {
      material: 'Silk and velvet blend with intricate zari work and hand-embroidered motifs, weighing 2.5 kg with a dense, plush weave',
      fit:      "Flared, floor-sweeping silhouette with a fitted bodice and a dramatic train. Model is 5'9\" wearing size M.",
      care:     'Dry clean only. Avoid exposure to direct sunlight and moisture. Iron on low heat with a pressing cloth.',
    },
  },
  {
    id: 'eid-anarkali-occasion',
    name: 'Eid Anarkali Suit',
    category: 'Occasion Wear',
    price: 'PKR 22,000',
    images: [
      'https://cdn.shopify.com/s/files/1/1732/6543/files/Pakistani_Anarkali_Eid_Dresses_for_Eid_2023_480x480.jpg?v=1678982546',
      'https://cdn.shopify.com/s/files/1/1762/5129/files/women-in-eid-clothing.jpg?v=1645871825',
      'https://i.pinimg.com/474x/7e/8b/63/7e8b63c9ebe09f6cc536b55b258f5126.jpg',
    ],
    image: 'https://cdn.shopify.com/s/files/1/1732/6543/files/Pakistani_Anarkali_Eid_Dresses_for_Eid_2023_480x480.jpg?v=1678982546',
    colors: [
      { name: 'Teal',        hex: '#008080' },
      { name: 'Dusty Rose',  hex: '#C4A09A' },
      { name: 'Antique Gold',hex: '#C6A75E' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'The Eid Anarkali Suit is a celebration of Pakistani festive dressing — a floor-length flared anarkali with hand-embroidered yoke, worn with a fine churidar and a matching dupatta. Conceived for Eid mornings and evening dawats alike.',
    details: {
      material: 'Georgette anarkali with thread embroidery on yoke; silk churidar; chiffon dupatta',
      fit:      "Flared floor-length anarkali with fitted sleeves. Model is 5'7\" wearing size S.",
      care:     'Dry clean only. Store flat.',
    },
  },
  // ─── WINTER WEAR ───────────────────────────────────────────────────────────
  {
    id: 'khair-winter-shawl-41',
    name: 'Sahar Cashmere Wrap',
    category: 'Winter Wear',
    price: 'PKR 32,000',
    images: [
      'https://i.pinimg.com/736x/e9/cb/20/e9cb2010615e91c8d02b6eb4834ac8a0.jpg',
      'https://www.786shop.com/images/large/6/m_Marjjan-orya-mrk-03-a-z1.jpg',
      'https://www.designerdhaage.com/cdn/shop/products/imrozia-serene-datak-e-khizaan-sp-k12-wagma-233654_600x.jpg?v=1636656887',
    ],
    image: 'https://i.pinimg.com/736x/e9/cb/20/e9cb2010615e91c8d02b6eb4834ac8a0.jpg',
    colors: [
      { name: 'Mocha',    hex: '#964B00' },
      { name: 'Cream',    hex: '#F5F5DC' },
      { name: 'Charcoal', hex: '#333333' },
    ],
    sizes: ['One Size'],
    description: 'Wrap yourself in the opulence of our Sahar Cashmere Wrap, featuring an exquisite blend of soft cashmere and warm wool. The subtle sheen and gentle drape evoke the serenity of a winter\'s morning in the Hunza valley.',
    details: {
      material: '80% Cashmere, 20% Merino Wool. Medium weight, soft twill weave with a subtle texture',
      fit:      "Oversized, draped silhouette. Model is 5'8\" wearing One Size.",
      care:     'Dry clean only. Store in a cool, dry place away from direct sunlight.',
    },
  },
  {
    id: 'zarina-wool-coat-42',
    name: 'Khayyam Woolen Overcoat',
    category: 'Winter Wear',
    price: 'PKR 32,000',
    images: [
      'https://www.786shop.com/images/large/6/m_Marjjan-orya-mrk-03-a-z1.jpg',
      'https://www.designerdhaage.com/cdn/shop/products/imrozia-serene-datak-e-khizaan-sp-k12-wagma-233654_600x.jpg?v=1636656887',
      'https://www.786shop.com/images/large/6/m_Marjjan-rmntq-skc-56-z1.jpg',
    ],
    image: 'https://www.786shop.com/images/large/6/m_Marjjan-orya-mrk-03-a-z1.jpg',
    colors: [
      { name: 'Mocha',          hex: '#964B00' },
      { name: 'Charcoal Grey',  hex: '#333333' },
      { name: 'Rich Burgundy',  hex: '#8B0A1A' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your winter wardrobe with our Khayyam Woolen Overcoat, carefully crafted from the finest wool to provide unparalleled warmth and sophistication. The fitted silhouette and subtle shoulder pads create a flattering, feminine shape, while the intricate button detailing adds a touch of understated elegance.',
    details: {
      material: '80% wool, 20% cashmere blend, 400gsm, woven in a dense twill weave for exceptional durability and warmth',
      fit:      "Fitted silhouette with a nipped-in waist. Model is 5'8\" wearing size S.",
      care:     'Dry clean only, do not iron or bleach, store in a cool, dry place.',
    },
  },
  {
    id: 'zarina-wool-coat-43',
    name: 'Sahar Woolen Long Coat',
    category: 'Winter Wear',
    price: 'PKR 28,000',
    images: [
      'https://www.designerdhaage.com/cdn/shop/products/imrozia-serene-datak-e-khizaan-sp-k12-wagma-233654_600x.jpg?v=1636656887',
      'https://www.786shop.com/images/large/6/m_Marjjan-rmntq-skc-56-z1.jpg',
      'https://www.yourlibaas.com/cdn/shop/files/2C5A0606.jpg?v=1756110658',
    ],
    image: 'https://www.designerdhaage.com/cdn/shop/products/imrozia-serene-datak-e-khizaan-sp-k12-wagma-233654_600x.jpg?v=1636656887',
    colors: [
      { name: 'Mocha',          hex: '#964B00' },
      { name: 'Charcoal Grey',  hex: '#333333' },
      { name: 'Cream',          hex: '#F5F5F5' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your winter style with the Sahar Woolen Long Coat, meticulously crafted from rich, plush wool to envelop you in warmth and sophistication. The sleek, streamlined silhouette falls effortlessly to the knee, while the subtle sheen of the fabric catches the light with every move.',
    details: {
      material: '80% wool, 20% polyester blend, 350gsm weight, woven in a dense twill weave for exceptional warmth and durability',
      fit:      "Slim-fit silhouette with a nipped-in waist. Model is 5'8\" wearing size S.",
      care:     'Dry clean only. Do not iron or bleach. Store in a cool, dry place.',
    },
  },
  {
    id: 'khair-winter-shawl-44',
    name: 'Sahar Winter Wrap',
    category: 'Winter Wear',
    price: 'PKR 18,000',
    images: [
      'https://peachmode.com/cdn/shop/files/1_BOB-2417-2073-DRUST-PEACHMODE_98c9e092-81c9-4aa6-8359-45beabadbbe6.jpg?v=1732366960&width=3719',
      'https://www.786shop.com/blogdata/images/large/Winter-Dress-16-10-24.jpg',
      'https://peachmode.com/cdn/shop/files/1_KTI-KS5301-BEIGE-PEACHMODE_c2861f96-5b72-4d04-911e-a0fb78fc6ec0.jpg?v=1734439706&width=3719',
    ],
    image: 'https://peachmode.com/cdn/shop/files/1_BOB-2417-2073-DRUST-PEACHMODE_98c9e092-81c9-4aa6-8359-45beabadbbe6.jpg?v=1732366960&width=3719',
    colors: [
      { name: 'Mocha',          hex: '#964B00' },
      { name: 'Charcoal Grey',  hex: '#333333' },
      { name: 'Cream',          hex: '#F5F5F5' },
    ],
    sizes: ['One Size'],
    description: 'Elegantly draped and meticulously crafted, the Sahar Winter Wrap is a masterclass in understated sophistication. This sumptuous shawl features a rich, velvety softness that envelops the senses, while its subtle sheen adds a touch of refinement to any outfit.',
    details: {
      material: 'Plush velvet with a subtle sheen, woven from a rich blend of 80% wool and 20% silk, 400gsm',
      fit:      "Oversized, draped silhouette with a relaxed fit. One Size fits all.",
      care:     'Dry clean only. Avoid exposure to direct sunlight or excessive moisture.',
    },
  },
  {
    id: 'khairat-khaddar-coat-12',
    name: 'Sahar Embroidered Wool Coat',
    category: 'Winter Wear',
    price: 'PKR 32,000',
    images: [
      'https://www.786shop.com/blogdata/images/large/Winter-Dress-16-10-24.jpg',
      'https://peachmode.com/cdn/shop/files/1_KTI-KS5301-BEIGE-PEACHMODE_c2861f96-5b72-4d04-911e-a0fb78fc6ec0.jpg?v=1734439706&width=3719',
      'https://www.yourlibaas.com/cdn/shop/files/2C5A0606.jpg?v=1756110658',
    ],
    image: 'https://www.786shop.com/blogdata/images/large/Winter-Dress-16-10-24.jpg',
    colors: [
      { name: 'Mocha',          hex: '#964B00' },
      { name: 'Charcoal Grey',  hex: '#333333' },
      { name: 'Ivory Cream',    hex: '#F5F5F5' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Wrap yourself in the warmth and elegance of our Sahar Embroidered Wool Coat, meticulously crafted with intricate floral patterns and subtle shine. The plush khaddar wool ensures a cozy fit, while the fitted silhouette accentuates your modest style.',
    details: {
      material: 'Rich khaddar wool with a soft, dense weave and a subtle sheen, weighing 400gsm for optimal warmth',
      fit:      "Fitted silhouette with a nipped-in waist and a dramatic flared hem. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Avoid exposure to direct sunlight and moisture.',
    },
  },
  // ─── ABAYAS ────────────────────────────────────────────────────────────────
  {
    id: 'zaynab-embroidered-abbaya-41',
    name: 'Zaynab Embroidered Abaya',
    category: 'Abayas',
    price: 'PKR 32,000',
    images: [
      'https://inayatarts.pk/wp-content/uploads/2023/10/7-1.jpg',
      'https://hijabulhareem.com/cdn/shop/files/2_285d9493-4961-4613-b0c3-35b891b2c988.jpg?v=1743646331',
      'https://pk-live-21.slatic.net/kf/S635d2bafdb1f4bda981ffe33d94909bbA.jpg',
    ],
    image: 'https://inayatarts.pk/wp-content/uploads/2023/10/7-1.jpg',
    colors: [
      { name: 'Midnight Blue', hex: '#1a1d23' },
      { name: 'Soft Mocha',    hex: '#c9c4b5' },
      { name: 'Cream Beige',   hex: '#f5f5dc' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Wrap yourself in elegance with the Zaynab Embroidered Abaya, featuring intricate traditional Pakistani motifs that dance across the fabric. This floor-sweeping abaya is perfect for special occasions, with a delicate balance of modesty and sophistication.',
    details: {
      material: 'Made from high-quality Nida fabric, a cotton-rich blend with a smooth texture and subtle sheen, weighing 250 grams per meter',
      fit:      "Fitted through the bodice with a flowing silhouette. Model is 5'8\" wearing size M.",
      care:     'Dry clean or hand wash in cold water. Iron while still slightly damp.',
    },
  },
  {
    id: 'majestic-dawn-abbaya-48',
    name: 'Zarina Abaya',
    category: 'Abayas',
    price: 'PKR 18,000',
    images: [
      'https://hijabulhareem.com/cdn/shop/files/2_285d9493-4961-4613-b0c3-35b891b2c988.jpg?v=1743646331',
      'https://pk-live-21.slatic.net/kf/S635d2bafdb1f4bda981ffe33d94909bbA.jpg',
      'https://fashionsense.com.pk/wp-content/uploads/2024/07/BZP_7857.webp',
    ],
    image: 'https://hijabulhareem.com/cdn/shop/files/2_285d9493-4961-4613-b0c3-35b891b2c988.jpg?v=1743646331',
    colors: [
      { name: 'Midnight Blue', hex: '#1a1d23' },
      { name: 'Soft Sage',     hex: '#bce3c5' },
      { name: 'Creamy Beige',  hex: '#f5f5dc' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Wrap yourself in elegance with the Zarina Abaya, featuring intricate embroidery that dances across the bodice, evoking the mystique of a moonlit night. This majestic abaya is crafted from a luxurious blend of silk and cotton, draping elegantly across the body.',
    details: {
      material: 'Silk and cotton blend, 400gsm, woven with a subtle sheen and a soft, smooth texture',
      fit:      "Relaxed, flowing silhouette with a V-neckline and long sleeves. Model is 5'8\" wearing size M.",
      care:     'Dry clean only. Avoid prolonged exposure to direct sunlight.',
    },
  },
  {
    id: 'khadijah-abay-42',
    name: 'Zahra Luxe Abaya',
    category: 'Abayas',
    price: 'PKR 32,000',
    images: [
      'https://suraiya.pk/wp-content/uploads/2025/04/grey-floral-embroidered-abaya-1.jpg',
      'http://www.dhaagey.pk/cdn/shop/files/Pearl-Rose-Abaya-by-Dhaagey-Abaya-_1.jpg?v=1748859132',
      'https://eastessence.com/cdn/shop/files/stitched-to-perfection-black-embroidered-abaya-215180.jpg?v=1756713998',
    ],
    image: 'https://suraiya.pk/wp-content/uploads/2025/04/grey-floral-embroidered-abaya-1.jpg',
    colors: [
      { name: 'Mocha',         hex: '#964B00' },
      { name: 'Midnight Blue', hex: '#1A1D23' },
      { name: 'Cream',         hex: '#F5F5F5' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your modest style with the Zahra Luxe Abaya, featuring intricate embroidery and a flowing silhouette that exudes elegance. The rich mocha hue is perfectly complemented by subtle gold accents, creating a truly regal look.',
    details: {
      material: 'Made from a luxurious blend of cotton and silk, this abaya boasts a smooth, lustrous finish and a comfortable weight that drapes beautifully',
      fit:      "Relaxed, floor-sweeping silhouette with a fitted sleeve and a subtle high-low hem. Model is 5'8\" wearing size M.",
      care:     'Dry cleaning or hand washing in cold water. Avoid machine washing and ironing on embroidery.',
    },
  },
  {
    id: 'saffron-dusk-abaya-42',
    name: "Zahra's Twilight Abaya",
    category: 'Abayas',
    price: 'PKR 18,500',
    images: [
      'http://www.dhaagey.pk/cdn/shop/files/Pearl-Rose-Abaya-by-Dhaagey-Abaya-_1.jpg?v=1748859132',
      'https://eastessence.com/cdn/shop/files/stitched-to-perfection-black-embroidered-abaya-215180.jpg?v=1756713998',
      'https://i0.wp.com/alsanaya.com/wp-content/uploads/2024/05/IMG_5707-1080x1620-1.webp?resize=430%2C430&ssl=1',
    ],
    image: 'http://www.dhaagey.pk/cdn/shop/files/Pearl-Rose-Abaya-by-Dhaagey-Abaya-_1.jpg?v=1748859132',
    colors: [
      { name: 'Saffron',   hex: '#F5DEB3' },
      { name: 'Dusk Blue', hex: '#6A5ACD' },
      { name: 'Cream',     hex: '#FFF599' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegance personified, the Zahra\'s Twilight Abaya envelops you in its soft, flowing folds, exuding a sense of refined modesty. The intricate embroidery adorning the neckline and cuffs shimmers like the night sky, while the saffron and dusk blue hues evoke the warm, golden tones of a Pakistani sunset.',
    details: {
      material: 'Made from a rich, high-quality Nida fabric with a subtle sheen, this abaya features a smooth, woven texture and a flowing drape',
      fit:      "Classic, flowing silhouette with a relaxed fit and a floor-sweeping length. Model is 5'8\" wearing size M.",
      care:     'Dry cleaning or gentle hand washing in cold water. Iron while still slightly damp.',
    },
  },
  {
    id: 'mashallah-abaya-51',
    name: 'Jamal-e-Nisa Abaya',
    category: 'Abayas',
    price: 'PKR 18,000',
    images: [
      'https://eastessence.com/cdn/shop/files/stitched-to-perfection-black-embroidered-abaya-215180.jpg?v=1756713998',
      'https://i0.wp.com/alsanaya.com/wp-content/uploads/2024/05/IMG_5707-1080x1620-1.webp?resize=430%2C430&ssl=1',
      'https://tgmstore.pk/cdn/shop/files/MidnightMuse_1_1080x.jpg?v=1753952580',
    ],
    image: 'https://eastessence.com/cdn/shop/files/stitched-to-perfection-black-embroidered-abaya-215180.jpg?v=1756713998',
    colors: [
      { name: 'Midnight Blue', hex: '#1a1d23' },
      { name: 'Soft Sage',     hex: '#bce3c5' },
      { name: 'Regal Black',   hex: '#000000' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elevate your modest wardrobe with the Jamal-e-Nisa Abaya, meticulously crafted with intricate embroidery and a flowing silhouette. The luxurious fabric drapes elegantly, creating a sense of refinement and poise. Perfect for special occasions or everyday wear.',
    details: {
      material: 'Rich cotton blend with a subtle sheen, 220gsm, woven with a dense twill weave for durability and comfort',
      fit:      "Relaxed, floor-sweeping silhouette with a fitted bodice. Model is 5'8\" wearing size M.",
      care:     'Dry clean or hand wash in cold water. Iron while slightly damp.',
    },
  },
];

export const shopProducts = products;